# Generated by Django 5.2.8 on 2025-11-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_mob', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$...', max_length=100)),
                ('login_status', models.BooleanField(default=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now=True, null=True)),
                ('eby', models.IntegerField(blank=True, null=True)),
                ('eat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=12)),
                ('priority', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.master_project')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='task.master_user')),
            ],
        ),
        migrations.AddField(
            model_name='master_project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='task.master_user'),
        ),
        migrations.AlterUniqueTogether(
            name='master_project',
            unique_together={('owner', 'name')},
        ),
    ]
