# Generated by Django 5.2.8 on 2025-11-20 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_user',
            old_name='user_id',
            new_name='u_id',
        ),
        migrations.AddField(
            model_name='master_user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
