# Generated by Django 5.2.8 on 2025-11-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_user_id_master_user_u_id_master_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_user',
            old_name='login_status',
            new_name='status',
        ),
    ]
