# Generated by Django 5.2.8 on 2025-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_login_status_master_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_user',
            name='user_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
