# Generated by Django 5.2.8 on 2025-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_master_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
